### PR TITLE
Update contracts.md

### PR DESCRIPTION
**Pull request by oculushut**
Updated broken link to configuration page.

### CODE REVIEW

**Comment by tcoulter** [comment]
This is invalid. The links don't need the `.md` extension. When developing Truffle documentation, run `npm run docs` within your Truffle checkout and that will give you a development version of the documentation you can work with. You'll see that those links work correctly. Cheers!

**Comment by oculushut** [comment]
Ah OK - I did not realise that this is was how the documentation was supposed to be viewed.  The first thing I did was review this documentation online - on the GitHub website.

I added the .md extensions as this made the links work when viewing via the GitHub website.  Perhaps others will do the same as me and try to read via the GitHub website initially before committing more time?

Great repo by the way.  Appreciate the time you have put into this!

**Comment by tcoulter** [comment]
That's a great point. I never thought of consuming the docs that way (my response seems harsh now, apologies). 

Let me see if those links will work on the documentation site, and if they do we can reopen this PR.

**Comment by tcoulter** [comment]
Hmm, unfortunately they don't. I wonder if there's another option.

**Pull request closed without merging**
