### PR TITLE
add babel-polyfill

### PR DESCRIPTION
**Pull request by jtremback**
I want to use async/await again

### CODE REVIEW

**Comment by lucasconstantino** [comment]
Meanwhile you can re-configure the polyfill in your "truffle.js" file, like so:

```
require("babel-polyfill");
require("babel-register")({
  "presets": ["es2015"],
  "plugins": ["syntax-async-functions","transform-regenerator"]
});

module.exports = {
  build: {
    "index.html": "index.html",
    "app.js": [
      "javascripts/app.js"
    ],
    "app.css": [
      "stylesheets/app.css"
    ],
    "images/": "images/"
  },
  deploy: [
    // "Contract"
  ],
  rpc: {
    host: "localhost",
    port: 8545
  }
};
```

(ref: http://masnun.com/2015/11/11/using-es7-asyncawait-today-with-babel.html)

**Comment by tcoulter** [comment]
I've hand-merged this into the `develop` branch, which includes the `migrations` branch changes. Can you guy ensure it's working as you expect? Note the `migrations` branch includes significant changes to Truffle and requires changes in your dapp. See here for more info: https://github.com/ConsenSys/truffle/pull/143

**Comment by tcoulter** [comment]
Please close if this works for you so it updates the milestone.

**Comment by tcoulter** [comment]
I've found that this addition breaks testing (and likely other things):

```
Error: Couldn't find preset "es2015" relative to directory "/Users/tim/Documents/workspace/Consensys/test"
```

This is likely because of this code added:

```
require("babel-register")({
  "presets": ["es2015", "stage-2"]
})
require("babel-polyfill")
```

I've changed it to this, and left it up to the user to specify their presets in their project's .babelrc.

```
require("babel-register");
require("babel-polyfill");
```

**Comment by tcoulter** [comment]
@lucasconstantino I *really* like your solution instead. Perhaps that should be the solution for all truffle projects that want to use babel. The Truffle requirement on babel is overkill since Truffle doesn't use babel internally.

**Comment by ethers** [comment]
thanks @lucasconstantino solution works for me

**Comment by cdyfng** [comment]
You can update your node to the newest version by following step. 
```
1. node -v     #may display version less then v8.0.0
2. sudo npm cache clean -f 
3. sudo npm install -g n
4. node -v  #check the version , mine is v8.0.0 now 
```
Test ok on Mac Os. 
Then you can use async/await in your js code.

**Pull request merged**
