### PR TITLE
Add the packaging metadata to build the truffle snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

To test it in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/truffle
    $ cd truffle
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous

This is just a simple yaml to help you get started. It needs more testing, and I am getting this error:
Error: Couldn't find preset "es2015"

I don't know a lot about javascript, but I'd be happy to help you on the packaging side.

If you have any questions or comments, please let me know.

**Comment by elopio** [comment]
ping. Anyone around to review this?

**Comment by tcoulter** [comment]
This appears to be [an advertisement](https://www.google.com/search?q=%22This+is+a+package+for+the+secure+installation+of+apps+that+works+in+most+Linux+distributions.+Landing+it+upstream+will+enable+builds+that+then+can+be+distributed+to+many+users+through+the+Ubuntu+store.%22&rlz=1C5CHFA_enUS710US710&oq=%22This+is+a+package+for+the+secure+installation+of+apps+that+works+in+most+Linux+distributions.+Landing+it+upstream+will+enable+builds+that+then+can+be+distributed+to+many+users+through+the+Ubuntu+store.%22&aqs=chrome..69i57.1471j0j4&sourceid=chrome&ie=UTF-8#q=%22This+is+a+package+for+the+secure+installation+of+apps+that+works+in+most+Linux+distributions.+Landing+it+upstream%22), so I'm going to close it. If there's legitimate interest wrt Truffle, please contact me on Gitter. Thanks.

**Comment by elopio** [comment]
What? 😰 no, not advertisement. 

In my team we are writing [snapcraft](https://github.com/snapcore/snapcraft/), and in order to validate our new features I'm constantly looking for interesting free projects to use them in a real world scenario. When we are done with the release, the `snapcraft.yaml` written for these test subjects is actually almost all of the effort required to put them in the Ubuntu store, so I send the PRs in case they want to make their software available there. The benefit for you as an upstream is that you can easily deliver your software to all of the Ubuntu users, and the benefit for us is that we can gather feedback from your experience with snaps and improve future releases. And then cycle starts again :)

We've already received some useful feedback from [monero](https://github.com/monero-project/monero/blob/master/snapcraft.yaml), [openbazaar](https://github.com/OpenBazaar/openbazaar-go/blob/master/snapcraft.yaml), [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/blob/develop/dist/snap/snapcraft.yaml), [ipfs](https://github.com/elopio/ipfs-snap)... Blockchain and distributed systems are a particular interest of mine, so I want us to provide a flawless experience for use cases like yours.

@tcoulter I have a legitimate interest in making truffle easily available to all Ubuntu users. But I couldn't figure out how to solve that `es2015` error. I would need some help from your side to get the packaging finished. I've just joined your gitter.

**Comment by tcoulter** [comment]
Thanks for the feedback. Google showed me similar PRs with much the same wording (i.e., insert project name <here>, and the rest was the same), so figured this submission was mostly automated. 

Though I do like making it more available for Ubuntu users, I don't have the bandwidth to test and ensure a new distribution channel continues to work correctly. When I look into new distribution methods (something I'll definitely do in the future) I'll look into snap.

Thanks!

**Comment by elopio** [comment]
@tcoulter I ran out of imagination for commit messages after working in a couple of projects :p
It's all right, thanks for taking a look. 

And for when you start looking into distribution, take into account that here we are leveraging the ubuntu community to develop and improve the software in the store. There are a lot of testers on the community, so when you put an unstable version in the edge channel it will be only visible to these early adopters who will help polishing the release until it is stable and ready to be made publicly available. We increase our bandwidth with crowdtesting, to support all the different platforms, architectures and crazy configurations out there. It might be useful for you too, and we'd be happy to help.

pura vida

**Comment by elopio** [comment]
@tcoulter I am now maintaining the [solidity](https://github.com/ethereum/solidity/blob/develop/snap/snapcraft.yaml) snap in the Ubuntu store. I'm looking for other useful tools to accompany it, and got back to truffle. I'm now confident that I can maintain truffle along with solc, but it would simplify a lot my tasks if the snapcraft.yaml is in the same repo as the upstream code.

Would you be ok merging it if I take care of maintaining it?

pura vida

**Pull request closed without merging**
